# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{minion}
  s.version = "0.1.15"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Orion Henry"]
  s.date = %q{2011-07-25}
  s.description = %q{Super simple job queue over AMQP}
  s.email = %q{orion@heroku.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/minion.rb",
    "lib/minion/handler.rb",
    "spec/base.rb",
    "spec/enqueue_spec.rb"
  ]
  s.homepage = %q{http://github.com/orionz/minion}
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{minion}
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Super simple job queue over AMQP}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<amqp>, ["= 0.7.4"])
      s.add_runtime_dependency(%q<bunny>, ["= 0.7.2"])
      s.add_runtime_dependency(%q<json>, [">= 1.2.0"])
    else
      s.add_dependency(%q<amqp>, ["= 0.7.4"])
      s.add_dependency(%q<bunny>, ["= 0.7.2"])
      s.add_dependency(%q<json>, [">= 1.2.0"])
    end
  else
    s.add_dependency(%q<amqp>, ["= 0.7.4"])
    s.add_dependency(%q<bunny>, ["= 0.7.2"])
    s.add_dependency(%q<json>, [">= 1.2.0"])
  end
end

